# Generated by Django 5.0.6 on 2026-06-19 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[('petrol_95', 'Benzyna PB95'), ('petrol_98', 'Benzyna PB98'), ('diesel', 'Diesel (ON)'), ('lpg', 'LPG'), ('electric', 'Ladowanie elektryczne (kWh)')], max_length=20)),
                ('liters', models.DecimalField(decimal_places=2, help_text="Dla elektrykow: ilosc kWh (pole nazwane 'liters' dla uproszczenia schematu)", max_digits=7)),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('odometer_km', models.PositiveIntegerField(help_text='Przebieg w momencie tankowania')),
                ('km_since_last_fillup', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('consumption_per_100km', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('station_name', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='fuel_receipts/%Y/%m/')),
                ('fueled_at', models.DateTimeField(help_text='Data i godzina tankowania')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='drivers.driver')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='scheduling.shift')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Tankowanie',
                'verbose_name_plural': 'Tankowania',
                'db_table': 'fuel_logs',
                'ordering': ['-fueled_at'],
                'indexes': [models.Index(fields=['vehicle', 'fueled_at'], name='fuel_logs_vehicle_3196db_idx'), models.Index(fields=['driver', 'fueled_at'], name='fuel_logs_driver__3cc88e_idx')],
            },
        ),
    ]
