# Generated by Django 5.0.6 on 2026-06-19 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('employment', 'Umowa o prace'), ('mandate', 'Umowa zlecenie'), ('b2b', 'Wspolpraca B2B')], max_length=20)),
                ('settlement_model', models.CharField(choices=[('fixed_rate', 'Stawka stala (godzinowa/dzienna)'), ('revenue_share', 'Procent od przychodu z kursow'), ('mixed', 'Stawka stala + procent od przychodu')], max_length=20)),
                ('fixed_rate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fixed_rate_period', models.CharField(blank=True, choices=[('hourly', 'za godzine'), ('daily', 'za dzien')], max_length=10, null=True)),
                ('revenue_share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('private_vehicle_compensation', models.DecimalField(blank=True, decimal_places=2, help_text='Rekompensata za uzywanie wlasnego pojazdu (np. zl/km lub ryczalt miesieczny)', max_digits=8, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, help_text='Puste = umowa na czas nieokreslony', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Umowa',
                'verbose_name_plural': 'Umowy',
                'db_table': 'employment_contracts',
            },
        ),
        migrations.CreateModel(
            name='SettlementPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle_compensation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Wersja roboca'), ('approved', 'Zatwierdzone'), ('paid', 'Wyplacone')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_periods', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Rozliczenie',
                'verbose_name_plural': 'Rozliczenia',
                'db_table': 'settlement_periods',
                'ordering': ['-period_start'],
                'unique_together': {('driver', 'period_start', 'period_end')},
            },
        ),
    ]
