# Generated by Django 5.0.6 on 2026-06-19 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pesel', models.CharField(help_text='Do umow i rozliczen z ZUS/US', max_length=11, unique=True)),
                ('hired_at', models.DateField(help_text='Data zatrudnienia')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('suspended', 'Zawieszony'), ('inactive', 'Nieaktywny'), ('terminated', 'Zwolniony')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kierowca',
                'verbose_name_plural': 'Kierowcy',
                'db_table': 'drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('taxi_license', 'Licencja na wykonywanie transportu taksowka'), ('driving_license', 'Prawo jazdy'), ('psychological_test', 'Badania psychologiczne'), ('occupational_medicine', 'Medycyna pracy'), ('medical_exam', 'Badania lekarskie (ogolne)'), ('criminal_record', 'Zapytanie o niekaralnosc'), ('other', 'Inny dokument')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, help_text='Np. nazwa urzedu, gminy, przychodni', max_length=200)),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField(db_index=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_documents/%Y/%m/')),
                ('alert_threshold_days', models.PositiveSmallIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Dokument kierowcy',
                'verbose_name_plural': 'Dokumenty kierowcy',
                'db_table': 'driver_documents',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['doc_type', 'expires_at'], name='driver_docu_doc_typ_75ef7a_idx')],
            },
        ),
    ]
