# Generated by Django 5.0.6 on 2026-06-28 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Zadanie zmiany e-mail',
                'verbose_name_plural': 'Zadania zmiany e-mail',
                'db_table': 'email_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
