# Generated by Django 5.0.6 on 2026-06-19 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzyna'), ('diesel', 'Diesel'), ('lpg', 'LPG'), ('hybrid', 'Hybryda'), ('electric', 'Elektryczny')], max_length=20)),
                ('ownership_type', models.CharField(choices=[('fleet', 'Auto firmowe'), ('private', 'Auto prywatne kierowcy')], default='fleet', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Aktywne'), ('in_service', 'W serwisie / naprawie'), ('retired', 'Wycofane z uzytku')], default='active', max_length=20)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('manufacturer_avg_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Srednie spalanie deklarowane przez producenta, l/100km', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vehicles', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Pojazd',
                'verbose_name_plural': 'Pojazdy',
                'db_table': 'vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('routine_service', 'Przeglad okresowy'), ('repair', 'Naprawa'), ('tire_change', 'Wymiana ogumienia'), ('oil_change', 'Wymiana oleju'), ('other', 'Inne')], max_length=30)),
                ('description', models.TextField()),
                ('service_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workshop_name', models.CharField(blank=True, max_length=200)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='maintenance_invoices/%Y/%m/')),
                ('next_service_due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('next_service_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Wpis serwisowy',
                'verbose_name_plural': 'Historia serwisowa',
                'db_table': 'maintenance_logs',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('oc_insurance', 'Ubezpieczenie OC'), ('ac_insurance', 'Ubezpieczenie AC'), ('technical_inspection', 'Przeglad techniczny'), ('taxi_permit', 'Zezwolenie na taksowke (pojazd)'), ('other', 'Inny dokument')], max_length=30)),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField(db_index=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_documents/%Y/%m/')),
                ('alert_threshold_days', models.PositiveSmallIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Dokument pojazdu',
                'verbose_name_plural': 'Dokumenty pojazdu',
                'db_table': 'vehicle_documents',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['doc_type', 'expires_at'], name='vehicle_doc_doc_typ_6f07ad_idx')],
            },
        ),
    ]
