# Generated by Django 5.0.6 on 2026-06-19 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('planned', 'Zaplanowana'), ('in_progress', 'W trakcie'), ('completed', 'Zakonczona'), ('cancelled', 'Odwolana')], default='planned', max_length=20)),
                ('odometer_start_km', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_end_km', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Dyspozytor, ktory utworzyl zmiane', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Zmiana',
                'verbose_name_plural': 'Zmiany (grafik)',
                'db_table': 'shifts',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['driver', 'start_at'], name='shifts_driver__faf844_idx'), models.Index(fields=['vehicle', 'start_at'], name='shifts_vehicle_2900a9_idx')],
            },
        ),
    ]
